spring.application.name=system_mk
# ===============================
# CONFIGURACIÓN DE LARAGON (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/minimarket_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# Esto hace que Spring cree las tablas en Laragon automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# PUERTO DEL MICROSERVICIO
# ===============================
# Como haremos 10 servicios, cada uno debe tener un puerto distinto.
# A productos le daremos el 8081.
server.port=8081